import type { SyntheticMedicationSource } from './validate-synthetic-source';

/**
 * Fictional catalogue rows for automated tests.
 * Names, codes, and authorization strings are synthetic. They are not clinical facts.
 */

const SOURCE = 'source.synthetic';
const VERSION = 'synthetic-2026-10-06';
const SEEN = '2026-10-06T00:00:00Z';

const missing = { status: 'missing' as const };

function present(value: string) {
  return { status: 'present' as const, value };
}

function strength(
  value: ReturnType<typeof present> | typeof missing,
  unit: ReturnType<typeof present> | typeof missing,
  originalText: ReturnType<typeof present> | typeof missing,
) {
  return {
    value,
    unit,
    originalText,
    denominatorValue: missing,
    denominatorUnit: missing,
  };
}

const dataSource = {
  sourceKey: SOURCE,
  name: 'Synthetic medication catalogue',
  authority: 'Fictional Test Authority',
  jurisdiction: present('fictional'),
  url: 'https://example.invalid/synthetic-medication-catalogue',
  licenseOrPermissionReference: present('synthetic-no-rights-granted'),
  rightsStatus: 'unresolved' as const,
  allowedUses: ['automated-test' as const],
  prohibitedUses: [
    'retrieval' as const,
    'server-storage' as const,
    'transformation' as const,
    'display' as const,
    'redistribution' as const,
    'offline-cache' as const,
    'commercial-use' as const,
  ],
  permissionExpiresAt: missing,
  attributionRequirements: present('Synthetic fixture. Not for clinical use.'),
  expectedUpdateCadence: missing,
  importMethod: 'synthetic-inline',
  coverageDescription:
    'Fictional products for automated tests. Not for clinical use.',
  reviewOwner: 'none',
  reviewedAt: SEEN,
};

const datasetVersion = {
  dataset: 'synthetic-medication-catalogue',
  version: VERSION,
  upstreamVersion: missing,
  publishedAt: missing,
  upstreamPublishedAt: missing,
  importedAt: SEEN,
  schemaVersion: 'medication-catalogue-1' as const,
  minimumClientVersion: '0.0.0',
  coverage: 'Fictional coverage only. Not for clinical use.',
  rightsApprovalReference: 'not-approved',
  clinicalReviewReference: 'not-reviewed',
  previousVersionKey: missing,
  status: 'staging' as const,
};

function tracked(sourceKey: string, datasetVersionKey: string) {
  return { sourceKey, datasetVersionKey };
}

const mainTrack = tracked(SOURCE, VERSION);

function mapping(sourceIngredientId: string) {
  return {
    sourceKey: SOURCE,
    sourceIngredientId,
    mappingVersion: 'synthetic-1',
    reviewStatus: 'unreviewed' as const,
  };
}

function ingredient(sourceRecordKey: string, preferredName: string) {
  return {
    ...mainTrack,
    sourceRecordKey,
    preferredName,
    originalNames: [preferredName],
    dci: missing,
    saltOrForm: missing,
    synonyms: [] as string[],
    externalMappings: [mapping(`MAP-${sourceRecordKey}`)],
    sourceVersion: 'synthetic-1',
  };
}

const commaName = 'Fict\u0103\u0219\u021B-\u0102\u00E2\u00EE';
const cedillaName = 'Fict\u0103\u015F\u0163-\u0102\u00E2\u00EE';

export const syntheticMedicationFixture = {
  synthetic: true as const,
  dataSource,
  datasetVersion,
  products: [
    {
      ...mainTrack,
      sourceProductId: 'SP-FICTIVOL',
      cim: present('FICT-CIM-0001'),
      commercialName: 'Fictivol',
      originalDciText: present('Fictivolinum'),
      strengthText: present('500 mg'),
      dosageFormKey: present('DF-TABLET'),
      route: present('oral-fictional'),
      atcKeys: ['ATC-SYN-01'],
      manufacturerKeys: ['MF-SYNTHETICA'],
      marketingAuthorizationHolderKey: present('MAH-PLACEBO'),
      authorizationNumber: present('AUTH-FICT-0001'),
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: ['RD-FICTIVOL'],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
    {
      ...mainTrack,
      sourceProductId: 'SP-PLACEBEX',
      cim: missing,
      commercialName: 'Placebex',
      originalDciText: missing,
      strengthText: present('100 mg/20 mg/5 mg'),
      dosageFormKey: present('DF-TABLET'),
      route: present('oral-fictional'),
      atcKeys: ['ATC-SYN-02'],
      manufacturerKeys: ['MF-SYNTHETICA'],
      marketingAuthorizationHolderKey: present('MAH-PLACEBO'),
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
    {
      ...mainTrack,
      sourceProductId: 'SP-SYNTHETICA-10',
      cim: missing,
      commercialName: 'Synthetica',
      originalDciText: missing,
      strengthText: present('10 mg'),
      dosageFormKey: present('DF-TABLET'),
      route: missing,
      atcKeys: [],
      manufacturerKeys: ['MF-SYNTHETICA'],
      marketingAuthorizationHolderKey: missing,
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
    {
      ...mainTrack,
      sourceProductId: 'SP-SYNTHETICA-20',
      cim: missing,
      commercialName: 'Synthetica',
      originalDciText: missing,
      strengthText: present('20 mg'),
      dosageFormKey: present('DF-CAPSULE'),
      route: missing,
      atcKeys: [],
      manufacturerKeys: ['MF-SYNTHETICA'],
      marketingAuthorizationHolderKey: missing,
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
    {
      ...mainTrack,
      sourceProductId: 'SP-VACANTOL',
      cim: missing,
      commercialName: 'Vacantol',
      originalDciText: missing,
      strengthText: missing,
      dosageFormKey: missing,
      route: missing,
      atcKeys: [],
      manufacturerKeys: [],
      marketingAuthorizationHolderKey: missing,
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'unresolved' as const,
    },
    {
      ...mainTrack,
      sourceProductId: 'SP-DIACRITIC-COMMA',
      cim: missing,
      commercialName: commaName,
      originalDciText: missing,
      strengthText: missing,
      dosageFormKey: missing,
      route: missing,
      atcKeys: [],
      manufacturerKeys: [],
      marketingAuthorizationHolderKey: missing,
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
    {
      ...mainTrack,
      sourceProductId: 'SP-DIACRITIC-CEDILLA',
      cim: missing,
      commercialName: cedillaName,
      originalDciText: missing,
      strengthText: missing,
      dosageFormKey: missing,
      route: missing,
      atcKeys: [],
      manufacturerKeys: [],
      marketingAuthorizationHolderKey: missing,
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
    {
      ...mainTrack,
      sourceProductId: 'SP-QUANTIX',
      cim: missing,
      commercialName: 'Quantix',
      originalDciText: missing,
      strengthText: present('0,5 µg'),
      dosageFormKey: present('DF-TABLET'),
      route: missing,
      atcKeys: [],
      manufacturerKeys: [],
      marketingAuthorizationHolderKey: missing,
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
    {
      ...mainTrack,
      sourceProductId: 'SP-UNITOX',
      cim: missing,
      commercialName: 'Unitox',
      originalDciText: missing,
      strengthText: present('1.000 xyz-not-a-unit'),
      dosageFormKey: missing,
      route: missing,
      atcKeys: [],
      manufacturerKeys: [],
      marketingAuthorizationHolderKey: missing,
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
    {
      ...tracked('source.missing', 'missing-version'),
      sourceProductId: 'SP-DANGLEBEX',
      cim: missing,
      commercialName: 'Danglebex',
      originalDciText: missing,
      strengthText: missing,
      dosageFormKey: present('DF-MISSING'),
      route: missing,
      atcKeys: ['ATC-MISSING'],
      manufacturerKeys: ['MF-MISSING'],
      marketingAuthorizationHolderKey: present('MAH-MISSING'),
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: ['RD-MISSING'],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'unresolved' as const,
    },
  ],
  activeIngredients: [
    ingredient('AI-FICTIVOLINUM', 'Fictivolinum'),
    ingredient('AI-PLACEBEXIUM', 'Placebexium'),
    ingredient('AI-SYNTHETINUM', 'Synthetinum'),
    ingredient('AI-FICTOVOL', 'Fictovolol'),
    ingredient('AI-SYNTHETONE', 'Synthetone'),
    ingredient('AI-QUANTIX', 'Quantixium'),
    ingredient('AI-UNITOX', 'Unitoxinum'),
  ],
  medicationIngredients: [
    {
      ...mainTrack,
      sourceRecordKey: 'MI-FICTIVOL',
      productSourceKey: 'SP-FICTIVOL',
      productSourceKeySource: SOURCE,
      ingredientKey: present('AI-FICTIVOLINUM'),
      sourceIngredientText: 'Fictivolinum',
      strength: strength(present('500'), present('mg'), present('500 mg')),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...mainTrack,
      sourceRecordKey: 'MI-PLACEBEX-1',
      productSourceKey: 'SP-PLACEBEX',
      productSourceKeySource: SOURCE,
      ingredientKey: present('AI-PLACEBEXIUM'),
      sourceIngredientText: 'Placebexium',
      strength: strength(present('100'), present('mg'), present('100 mg')),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...mainTrack,
      sourceRecordKey: 'MI-PLACEBEX-2',
      productSourceKey: 'SP-PLACEBEX',
      productSourceKeySource: SOURCE,
      ingredientKey: present('AI-SYNTHETINUM'),
      sourceIngredientText: 'Synthetinum',
      strength: strength(present('20'), present('mg'), present('20 mg')),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...mainTrack,
      sourceRecordKey: 'MI-PLACEBEX-3',
      productSourceKey: 'SP-PLACEBEX',
      productSourceKeySource: SOURCE,
      ingredientKey: present('AI-FICTOVOL'),
      sourceIngredientText: 'Fictovolol',
      strength: strength(present('5'), present('mg'), present('5 mg')),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...mainTrack,
      sourceRecordKey: 'MI-SYNTHETICA-10',
      productSourceKey: 'SP-SYNTHETICA-10',
      productSourceKeySource: SOURCE,
      ingredientKey: present('AI-SYNTHETONE'),
      sourceIngredientText: 'Synthetone',
      strength: strength(present('10'), present('mg'), present('10 mg')),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...mainTrack,
      sourceRecordKey: 'MI-SYNTHETICA-20',
      productSourceKey: 'SP-SYNTHETICA-20',
      productSourceKeySource: SOURCE,
      ingredientKey: present('AI-SYNTHETONE'),
      sourceIngredientText: 'Synthetone',
      strength: strength(present('20'), present('mg'), present('20 mg')),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...mainTrack,
      sourceRecordKey: 'MI-VACANTOL',
      productSourceKey: 'SP-VACANTOL',
      productSourceKeySource: SOURCE,
      ingredientKey: missing,
      sourceIngredientText: 'Vacantolum',
      strength: strength(missing, missing, missing),
      mappingStatus: 'unresolved' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...mainTrack,
      sourceRecordKey: 'MI-QUANTIX',
      productSourceKey: 'SP-QUANTIX',
      productSourceKeySource: SOURCE,
      ingredientKey: present('AI-QUANTIX'),
      sourceIngredientText: 'Quantixium',
      strength: strength(present('0,5'), present('µg'), present('0,5 µg')),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...mainTrack,
      sourceRecordKey: 'MI-UNITOX',
      productSourceKey: 'SP-UNITOX',
      productSourceKeySource: SOURCE,
      ingredientKey: present('AI-UNITOX'),
      sourceIngredientText: 'Unitoxinum',
      strength: strength(
        present('1.000'),
        present('xyz-not-a-unit'),
        present('1.000 xyz-not-a-unit'),
      ),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
    {
      ...tracked('source.missing', 'missing-version'),
      sourceRecordKey: 'MI-DANGLEBEX',
      productSourceKey: 'SP-DANGLEBEX',
      productSourceKeySource: 'source.missing',
      ingredientKey: present('AI-MISSING'),
      sourceIngredientText: 'Danglinum',
      strength: strength(missing, missing, missing),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
  ],
  atcCodes: [
    {
      ...mainTrack,
      sourceRecordKey: 'ATC-SYN-01',
      code: 'SYN-FICT-01',
      codeSystem: 'synthetic-illustrative' as const,
      illustrative: true as const,
      displayName: present('Synthetic illustrative class 01'),
      classificationVersion: missing,
    },
    {
      ...mainTrack,
      sourceRecordKey: 'ATC-SYN-02',
      code: 'SYN-FICT-02',
      codeSystem: 'synthetic-illustrative' as const,
      illustrative: true as const,
      displayName: present('Synthetic illustrative class 02'),
      classificationVersion: missing,
    },
  ],
  dosageForms: [
    {
      ...mainTrack,
      sourceRecordKey: 'DF-TABLET',
      displayName: 'fictional tablet',
      originalSourceText: 'fictional tablet',
      externalCode: missing,
    },
    {
      ...mainTrack,
      sourceRecordKey: 'DF-CAPSULE',
      displayName: 'fictional capsule',
      originalSourceText: 'fictional capsule',
      externalCode: missing,
    },
  ],
  manufacturers: [
    {
      ...mainTrack,
      sourceRecordKey: 'MF-SYNTHETICA',
      name: 'Synthetica Laboratories',
      country: missing,
      sourceEntityId: missing,
    },
  ],
  marketingAuthorizationHolders: [
    {
      ...mainTrack,
      sourceRecordKey: 'MAH-PLACEBO',
      name: 'Placebo Holding',
      country: missing,
      sourceEntityId: missing,
    },
  ],
  regulatoryDocuments: [
    {
      ...mainTrack,
      sourceRecordKey: 'RD-FICTIVOL',
      productSourceKey: 'SP-FICTIVOL',
      productSourceKeySource: SOURCE,
      type: 'other' as const,
      title: present('Fictional Fictivol note'),
      url: 'https://example.invalid/fictivol',
      language: present('ro'),
      documentVersion: missing,
      publishedAt: missing,
      retrievedAt: missing,
      lastCheckedAt: SEEN,
      sourceVersion: 'synthetic-1',
      cachedContentReference: missing,
      cacheRightsStatus: 'not-assessed' as const,
      checksum: missing,
    },
  ],
} satisfies SyntheticMedicationSource;

const SWAP = 'source.swap';
const SWAP_VERSION = 'synthetic-swap-1';
const swapTrack = tracked(SWAP, SWAP_VERSION);

export const syntheticSwapFixture = {
  synthetic: true as const,
  dataSource: {
    ...dataSource,
    sourceKey: SWAP,
    name: 'Synthetic swap catalogue',
    url: 'https://example.invalid/synthetic-swap-catalogue',
  },
  datasetVersion: {
    ...datasetVersion,
    dataset: 'synthetic-swap-catalogue',
    version: SWAP_VERSION,
    coverage: 'One fictional swap product. Not for clinical use.',
  },
  products: [
    {
      ...swapTrack,
      sourceProductId: 'SP-SWAPEX',
      cim: missing,
      commercialName: 'Swapex',
      originalDciText: missing,
      strengthText: missing,
      dosageFormKey: missing,
      route: missing,
      atcKeys: [],
      manufacturerKeys: [],
      marketingAuthorizationHolderKey: missing,
      authorizationNumber: missing,
      authorizationDate: missing,
      authorizationStatus: missing,
      presentationOrPackDescription: missing,
      regulatoryDocumentKeys: [],
      sourceVersion: 'synthetic-1',
      firstSeenAt: SEEN,
      lastSeenAt: SEEN,
      status: 'active' as const,
    },
  ],
  activeIngredients: [
    {
      ...swapTrack,
      sourceRecordKey: 'AI-SWAPEX',
      preferredName: 'Swapexium',
      originalNames: ['Swapexium'],
      dci: missing,
      saltOrForm: missing,
      synonyms: [] as string[],
      externalMappings: [
        {
          sourceKey: SWAP,
          sourceIngredientId: 'MAP-AI-SWAPEX',
          mappingVersion: 'synthetic-1',
          reviewStatus: 'unreviewed' as const,
        },
      ],
      sourceVersion: 'synthetic-1',
    },
  ],
  medicationIngredients: [
    {
      ...swapTrack,
      sourceRecordKey: 'MI-SWAPEX',
      productSourceKey: 'SP-SWAPEX',
      productSourceKeySource: SWAP,
      ingredientKey: present('AI-SWAPEX'),
      sourceIngredientText: 'Swapexium',
      strength: strength(missing, missing, missing),
      mappingStatus: 'confirmed' as const,
      mappingVersion: 'synthetic-1',
    },
  ],
  atcCodes: [],
  dosageForms: [],
  manufacturers: [],
  marketingAuthorizationHolders: [],
  regulatoryDocuments: [],
} satisfies SyntheticMedicationSource;
